### ISSUE TITLE
Bank Interest

### ISSUE THREAD

**Issue by PandaChristina** [drewhoener/JWSuggestions#124]
Just a little disclaimer here, this idea was completely created by Brawler,

We were wondering if this would really be a good and fair idea if every (or maybe just higher ranks) donator rank had a higher interest in /bank. Obviously, not by much at all- but enough for it to be noticeable depending on your rank. There's nothing really more to this, we just thought it would be an interesting suggestion. ;p

**Comment by PancakezOnMC** [comment]
Yeah. >:3

**Comment by SlandersPete** [comment]
I like the idea!

**Comment by 5d100** [comment]
I support this.

**Comment by PianoPlayingHusky** [comment]
We are all supporting this because we're donators ourselves xD

**Comment by 5d100** [comment]
well, considering that it's incentive to donate...

**Comment by WolfyCraft** [comment]
i like the idea

**Comment by drewhoener** [comment]
true, but bank accounts were never created to be a way to make money, they were made for shop owners to hide their money so that people couldn't sell them into bankruptcy...We kept the interest (albeit at a lower rate) because I argued with johnny that it was a nice perk for keeping money there. For that reason, I really can't implement this idea
