### ISSUE TITLE
Mature Chat Channel

### ISSUE THREAD

**Issue by Violaessence** [drewhoener/JWSuggestions#160]
./cc M (Mature) --- This is a channel that is ignored for players by default, if players want to go into this chat they must unignore it and confirm their age to a mod, from there inside of this channel you are allowed to say more mature things, this gives players who want to speak without fear of the auto-mute to speak.

**Comment by Zefferis** [comment]
I like the idea,

Not necessarily sure about going about verifying someone's age but I think the mature cc would be permissible if a non-disclosed unless un-ignored addendum is added to the rules; specifically the global rule:

"Do not use profanity, sexual content, or spam in the chat with any language"
- The only exception to this being the mature channel.

The drama rule still stands and insures, or gives grounds to remove people who use offensive language towards an individual rather than as a form of expression or discussion topic.

_________

For age verification I think the only way to go about this would be leaving the mature channel to donors (who would have needed some sort of credit card for instance to gain status) then to verify using an outside social media site? (Such that of FB/Twitter?) with a short dialogue between that person and the server account to verify?

That seems like a lot of extra work though /:

**Comment by duran5743** [comment]
Idk with a social media site its easy to lie about your age over the internet

**Comment by Violaessence** [comment]
Any word on this?

**Comment by drewhoener** [comment]
Referenced in #168 in more detail, issue closed
