### ISSUE TITLE
Cancel Bids

### ISSUE THREAD

**Issue by TemperrroniPizza** [drewhoener/JWSuggestions#176]
I've been outsniped too many times, and then I bid on things like 3 healing pots for 1500 coins, and I cant cancel the bid and everyone bullies me for it. /bidcancel would be great because it allows players to cancel their bids, for example you press enter too late, and you bid on the next thing. 
-Or you could add a 5 second gap between aucs. To avoid overshooting a snipe.

**Comment by TemperrroniPizza** [comment]
![2016-08-01_20 25 05](https://cloud.githubusercontent.com/assets/13492480/17316269/59162f0e-5827-11e6-8498-a1f667832f40.png)
![2016-08-01_20 25 09](https://cloud.githubusercontent.com/assets/13492480/17316273/5ce877cc-5827-11e6-826b-88c5bebfc1a5.png)
this is an example

**Comment by TemperrroniPizza** [comment]
Something that kinda upsets me is staff just lets it fly.

**Comment by TemperrroniPizza** [comment]
Can't there be a cap as to how much a certain item sells for?

**Comment by drewhoener** [comment]
If you wait until the last second, you have to expect that the ending price might be high
It's the risk of doing that

**Comment by drewhoener** [comment]
If you make the choice to wait until the very last second and bid up whatever price came before then that's your problem, and to put it on the staff seems very disrespectful

**Comment by drewhoener** [comment]
And what am I supposed to do, figure out reasonable price caps for every single item in the game? the entire point of an auction is that if someone REALLY wants something, they can outbid everyone else by however much they choose, why would I reinvent what an auction is becuase you bid too much without thinking? 
I can look into a command to cancel bids (I haven't worked much with my auction code since its release), but I think it's quite immature to claim that something is a scam and blame it on the staff when you purposefully wait until the last second to bid up whoever decides to snipe at the end, and I want that on record

**Comment by drewhoener** [comment]
Actually, I take back about looking into cancelling bids.
Say someone cancells their bid, and they're currently winning. Who does the auction fall to then? The last person to bid? Now that's more data that I have to save, for every single auction in the queue and in memory, I have to keep an extra string, uuid and 2 more price points to save and load every time we read/write to databases. Which very quickly takes my concept of a simple and lightweight auction plugin and bogs it down into the mud.

**Comment by TemperrroniPizza** [comment]
I was kinda upset for the chat driving me into silence, and everything I say afterwards is me triggered. So, I took the time to grind it back in about 7 minutes.

**Comment by TemperrroniPizza** [comment]
I'll delete this post if I can. Sorry for the shitty post.
