### ISSUE TITLE
Adding a "flat" build world

### ISSUE THREAD

**Issue by NightHawk164** [drewhoener/JWSuggestions#21]
I would suggest a sponged flat build world where players could buy the plots. I always get really sick of flattening out land before I build and town plots are just too... small. This way, people can build whatever they would like without digging their way in and having it all sponged like plots would allow other players to buy the plots as well.

**Comment by Spazgazum** [comment]
+1 support.

**Comment by SarabiMami** [comment]
I support this. I get so so tired wasting soo much time flattening and leveling areas all the time. I would definitely buy a plot or plots depending on how you regulate it.

**Comment by littletntman** [comment]
It's useful for town plots because you don't have to waste time

**Comment by Spazgazum** [comment]
It would be great for towns and shops.

Also, it would be great for testing builds, especially redstone builds. 

I have a single player world I call Redstone Playground that I switch back and forth between when testing things, but having a flat world would make it much simpler. 

Again this was an idea I was unsure of to begin with, but the longer I go without it, the more I want it. Lol.

Anyways..... It twould be cool. : )

(Thanks for reading and have a nice day.)

(P.S. This server is awesome!)

**Comment by hoogkerker** [comment]
It's survival, I honestly think it's part of the game to flatten land.
it also gives me a kind of feeling I achieved something when I flattened land for a build/ town.
I agree it's "usefull" if you're lazy.
but it just takes away the value of towns, because that way every one can easily make a town they just place a few blocks to mark the plots.
as I already said it's survival, not how to play the laziest person in mc ;p
so -1

**Comment by SarabiMami** [comment]
So the point for me is most people who play this are very young an are only allowed to play a few hours aday, due to parents, school, shared computers as for the older people a lot of people work and go to university etc....so spending your little bit of free time having to strip an area is not always feasible or worth it. 
I don't believe The plots should be allowed to be used by towns, official  towny or not. (Because people love to try to get around rules) also shops/bakeries and cafes should not be allowed  either. Otherwise they will fill the area and not use the shop portal area. However if you did let shops/bakeries/cafes or towns use these plots they should have to pay a higher price Or somthing.
I think there's should be a decently expensive price attached to each plot which prevents laziness In a way, just my ideas and opinions. I want this area not beca use of laziness, but because of time constraints For myself and others. I'd be willing to do the work to afford a hefty price for preflattened land, and I'm sure many others would as well. While lazy people won't want to make the money to use the area.

**Comment by hoogkerker** [comment]
well it's survival, you come here to play survival, not to build in a plot or something, I agree with your statement, though you come to us to play survival, and you have alot of people around who you can hire for some money to flatten, that way you get a good community too and everyone gets something to do, I am not a fan of preflattened area, just yeah, idk it's not my thing ;p

**Comment by Waffleflappers** [comment]
I would say that I am against this because it's basically just sprouting out of laziness. Part of your build being so amazing or impressive, is that you took time to flatten the land you built on. It just doesn't seem right to hop on over to survival plots and build there. Also, some players could take advantage of this and claim plots right next to other players who are active on their plots, and build some form of automatic farm that will work even when they aren't there because that other player would be on their plot. I just don't like it, so yeah -1

**Comment by Waffleflappers** [comment]
And Sarabi, your point about flattening being time consuming, so it's not out of laziness that you would do this, because you worked for the money. Well, working for money for a somewhat pricey plot I'm sure would take much more time than it takes to flatten land.

**Comment by BlueKnightSam** [comment]
-1 as well It's survival deal with it. What's the fun if everything is done for you? It becomes very boring and at that point not even worth it.

**Comment by PanicStingray77** [comment]
I also think that You know.... The land scape around your house is what makes it look even more awesome! so why take that away?

**Comment by BlueKnightSam** [comment]
As seeing this idea has more negative support than positive, what do you want to do @johnnywoof or @drewhoener

**Comment by drewhoener** [comment]
I think, for an ultimatum, the answer is no. We are a Survival PvE server, what's the fun if the environment doesn't fight back? xD not the perfect example I know, but the argument stands
