### ISSUE TITLE
Levels

### ISSUE THREAD

**Issue by NightHawk164** [drewhoener/JWSuggestions#22]
An awesome thing to implement onto this server is being able to "store" levels. I know that you can BUY levels using /buytemp but if we're able to store our own levels, that would be awesome. That way, we can pull up our levels for enchanting easier and when we die, it'll be okay. Also when a player reaches 50+ levels, the levels become useless and the player is forced to enchant.

**Comment by drewhoener** [comment]
What do you suggest? Making the books with your own levels?

**Comment by Spazgazum** [comment]
I'll be honest initially I really didn't like this idea, but after thinking about it a couple of days I may have changed my mind. I do have to say though I believe that there next to be some sort of restriction. I was thinking a maybe make where you have to have 50 levels then you can save 30 to a book or something that was just my first idea. Mainly just because it is really easy to get from 0 to 30, but takes a little time and work to get from 20 to 50.

**Comment by Spazgazum** [comment]
I'll be honest initially I really didn't like this idea, but after thinking about it a couple of days I may have changed my mind. I do have to say though I believe that there needs to be some sort of restriction. I was thinking maybe make it where you have to have 50+ levels then you can save 30 to a book or something, that was just my first idea. Mainly just because it is really easy to get from 0 to 30, but takes a little time and work to get from 20 to 50.



Edited: Due to autocorrect and poor wording.

**Comment by OoveVolcae** [comment]
Buying and selling levels, at least, is very possible.  It could also add a unique bit to the market. I've seen a few servers use it before. I'm not actually sure how it works, but it's definitely able to be done some how.  As for storing, I've seen a mod that has a chest you can store levels in. I don't know if that's doable, but I think adding levels to books would be interesting. If you had a 'level book' could you use commands similar to the bank to deposit, withdraw, and check the balance of xp in the book?

**Comment by drewhoener** [comment]
Actually, I already implement an item I coded on the server that gives you enough levels to get from lv. 0 - lv. 30 in one go. All I (should) have to do is take levels and create a book, though I was thinking for a cost, it shouldn't be free imo

**Comment by OoveVolcae** [comment]
Is there any way to make it a crafting recipe that requires a book, xp, and another item? That would have to be done at the anvil if so, no? I mean, if you used different resources to transfer different levels to books it would make them more expensive and possibly reduce the possible number in existence (book+iron+2lvls = 1lvl book, book+diamond+10lvls = 10lvl book, etc.). Otherwise, could it be made so that there's a tax on the xp to create the item? Ten levels of xp gives you a book with only 9 levels? My vote would be for uniformed books containing certain amounts of xp and/or levels, because then it would be easier to buy, sell, and trade. Is there any way to make it so an xp book could be sold in a shop? It would be a unique addition to many stores. 

However, this would also need a way to keep it from overloading the server with enchanted goods. When they are easy to obtain because anyone can be that level for a cheap cost, then we have a surplus of OP weapons, like the spawner pick. So I'd imagine there would have to be something to regulate that.

Just spouting off what's on my head. I don't know how it works, just some thoughts.

**Comment by drewhoener** [comment]
I'd love to do it in an anvil, but I'm not sure how much work it would be to actually make it happen, I don't think that there's recipe implementation for it. I like the idea of it costing more xp than will be put on the book, though I also think that there should be a coin cost. Also I want to keep in mind, is this taking away from regular players playing the game? they won't have to go to a mob grinder, they'll just have to buy a book from someone who already did the hard work for them. I just think that in this way people are gonna be lazier about grinding for resources.

**Comment by OoveVolcae** [comment]
Well they would still have to purchase the levels, which are easy to earn anyway. If there was a heavy enough tax then it would make books much more valuable and reduce the amount of xp people would get, thus meaning more work. As for how it works, I don't code so I have no idea I would imagine that if the anvil takes xp away to give new items the new item could be controlled. So a book and an ore (ie-diamond) could, at the cost of 25 xp, give a 20 level xp book?

**Comment by SarabiMami** [comment]
I wasn't interested in this initially as I was afraid it would make players even lazier lol....but  interested in it now after seeing everyone's comments.

**Comment by OoveVolcae** [comment]
Some would get lazier, sure, but others would work harder. And if we make it cost enough they have to still work to get the levels, just different kinds of work.

**Comment by littletntman** [comment]
I like this idea because if you die your levels are safe

**Comment by 5d100** [comment]
sounds good to me

**Comment by drewhoener** [comment]
I tried, the API doesn't support removing xp well, so it's a no go
