### ISSUE TITLE
Death Points

### ISSUE THREAD

**Issue by SonOfDeath** [drewhoener/JWSuggestions#5]
I had no idea what to put in as a title so that will have to do :)

When you die you lose all of your stuff and for people that do not have /back, that's really unfortunate and too many times have I seen people be like "I need to get my stuff back" or "Where did I die" only to their disappointment to find that we cannot help them. 

How about when you die, the server will tell you the Cords where you died at (The XYZ thing)?

Please let me know if these suggestions are helping :)

-Son_Of_Death

**Comment by drewhoener** [comment]
Sounds like a good idea

**Comment by Pheonixx** [comment]
While i understand the frustrations of losing all your stuff, this is a survival server, there should be consequences to dying. Death chests already give people a huge opportunity to reclaim items, 15 minutes to get to the chest before the chest despawns, then 5 more minutes before the items despawn off the ground. Giving the coordinates to the death chests would completely defeat the purpose of playing on a survival server.

**Comment by SonOfDeath** [comment]
I get what you're saying, but giving points is not as survival-breaking as you may think.

 As Lords we can do /god so we can never die and even if we do we have /back so we can get back easily. If that is not survival breaking I dunno what is.

What I'm trying to say is it is not breaking the gamemode as much as you think it is, and in certain ways the death point wont matter if you fell into lava or fell out of the world!

**Comment by Pheonixx** [comment]
while this is true, i and several others rarely have /god activated, as it makes the game too easy. and Death chests still spawn in Lava, so it does matter. falling out of the world hurts everyone... yes /god may "break" survival mode, but so does flying tbh..... i'm not saying it will break it, i'm saying it would make it pointless because it would take away any consequence to actually dying, as it would no longer have any effect on game play. died again, oh well, just run and get my stuff, no big deal, i know where it is. i think it would take away the point of the game. some people have the perks to be invincible, but it was due to donating, so i think that's different. and of course this is all how i feel personally. i just feel it would make things way to easy and take away the fear of dying. whats to fear if you loose nothing? i played on a server that had the loose inventory option turned off, and if it hadn't been for another mod on the server, it wouldn't have been nearly as fun, and i wouldn't have stuck around. again, just my personal thoughts and feelings on the matter.

**Comment by SonOfDeath** [comment]
I like how you think Mel :+1:

**Comment by SarabiMami** [comment]
While I agree to an extent with Mel, at the same time... i really don't think it would make it too easy.
First there are sooo many players who could not find a particular coordinates to save their life..items actually. Also even if you are familiar with coordinates it still takes time to get back there on foot if you can't fly. Plus as a donator I am often frustrated by how many times using /back does not take me to my last location. Sometimes i get lucky and it takes me to above it, as in i was deep underground and it takes me topside. while other times more often than not lately now that server has been acting weird/buggy it takes me somehwere else or at least a far distance away. This happens very often for me and my two irl donator friends who play on this server. (Lililya and Spazgazum) I lost a very nice sword and pick today because i could not get back to it today after /back did not take me where it was supposed to in the nether. That place has very few ways to mark your way/ natural monuments to get back to your stuff.
 So having the coordinates would definitely make us less frustrated. So I'd love to have that option.

**Comment by SonOfDeath** [comment]
The thing with /back is you cannot really use it underground..

if you try to use it it will bring you to the surface of that point. so where you were is exactly underneath where you were.

So you could just dig down to get back to where you were. /back will only remember places you: Teleported to, died at, teleported away from.

**Comment by drewhoener** [comment]
Interesting. I didn't know it did that. If that is actually an issue could you split that into a separate ticket?

**Comment by SarabiMami** [comment]
It doesn't do it every time.  It's not even predictable like that. It does it often yes. However mainly in the mineworld. As a matter of fact I have an underground base that is bedrock to an uneven 16 and I've never had any problem with/back to it.
It wasn't doing this until the last month or so, I wasn't having problems with it before then.

**Comment by SonOfDeath** [comment]
Ive always had some problems with /back underground.

**Comment by Spazgazum** [comment]
#CouldBeADonorPerk

**Comment by SonOfDeath** [comment]
It already is, /back

**Comment by Spazgazum** [comment]
A lower teir perk.

**Comment by johnnywoof** [comment]
Pro donator perk maybe?

**Comment by Spazgazum** [comment]
That's what I thought. Pro. That way it's not survival breaking any more so than other donor perks, Its still easy to get, and it works as a build up like the max homes does. 

First donation you get to find out where you died, next donation you get to /back there.

**Comment by drewhoener** [comment]
This should have been deployed by now, closing it
