### ISSUE TITLE
Armor Enchantments

### ISSUE THREAD

**Issue by Waffleflappers** [drewhoener/JWSuggestions#63]
I would like to see another custom enchantment for armor. Now, what I'm thinking of may not be codable, I'm not sure, but here it is. An armor enchant that is only applied if you are wearing full armor of one type, full iron armor, for example. Let's say the enchantment, "Buff"(random name), is on each piece of the iron armor you are wearing, and that is the only way it works. So you have Boots, Leggings, Chestplate, and a helm with Buff. Let's say Buff gave you more bars of armor or something of that sort. This is obviously just an example, but I hope you can understand the basic concept.

**Comment by johnnywoof** [comment]
`I would like to see another custom enchantment for armor.`
Like?
`Now, what I'm thinking of may not be codable, I'm not sure, but here it is.`
It can be coded.
`This is obviously just an example, but I hope you can understand the basic concept.`
I do understand your example, but due to your post being somewhat answered I'll be closing it.

**Comment by Waffleflappers** [comment]
The first part of me mentioning another custom enchantment was the enchantment given in my example.

**Comment by drewhoener** [comment]
I intend to add some sort of enchant in the future that will only give you the full effect if you wear a full set of the armor that all have that enchant, not sure what the effects will be though
