### ISSUE TITLE
New perk idea: /particles!

### ISSUE THREAD

**Issue by TemperrroniPizza** [drewhoener/JWSuggestions#79]
Hello, Drew! How are you doing today? I have a great idea for a new donator perk, called Particles! This applies to all donators like the mob disguises. So, with every rank comes its specific set of custom particles, some are from the Particle Generators in /buytemp, and some are donators only, except, you can have these particles permanently. This would be a great idea, because not only are particle generators, expensive, they are a temporary thing. This would be a great perk to add, simply for a better way to stand out, as a donator. Whenever you donate to a higher rank you get extra particle effects, like fire rings, or XP that rings around you. Thanks for taking your time upon reading this, and have a nice day.

**Comment by Duran1** [comment]
I love this idea

**Comment by drewhoener** [comment]
I've considered it at multiple times, but the conclusion I always come to is that we fix the price of something that no one can have normally.

Since we provide it to everyone at the same ingame price, no one has an advantage in real life, in terms of real money. I don't want to provide something that I've fixed a price on, for free to someone who happened to chuck a couple bucks at the server.

That said, there have been suggestions for enchantments with custom particle effects on them, which I think is a good idea, and one that I'll consider in the future
